# Generated by Django 2.2.5 on 2020-06-02 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200602_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 15, 29, 41, 715337, tzinfo=utc)),
        ),
    ]
